on:
  release:
    types: [published]

jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download Windows
        id: download-windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: nk-shootout-Windows.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Windows)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: nk-shootout
          ITCH_USER: zafuzi
          PACKAGE: nk-shootout-Windows.zip
          VERSION: ${{ steps.download-windows.outputs.version }}

  release_macos:
    runs-on: ubuntu-latest
    steps:
      - name: download MacOS
        id: download-macos
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: nk-shootout-MacOS.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (MacOS)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: nk-shootout
          ITCH_USER: zafuzi
          PACKAGE: nk-shootout-MacOS.zip
          VERSION: ${{ steps.download-windows.outputs.version }}

  release_linux:
    runs-on: ubuntu-latest
    steps:
      - name: download Linux
        id: download-linux
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: nk-shootout-Linux.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Linux)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: nk-shootout
          ITCH_USER: zafuzi
          PACKAGE: nk-shootout-Linux.zip
          VERSION: ${{ steps.download-windows.outputs.version }}
          
  release_html:
    runs-on: ubuntu-latest
    steps:
      - name: download HTML5
        id: download-html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: nk-shootout-HTML5.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: nk-shootout
          ITCH_USER: zafuzi
          PACKAGE: nk-shootout-HTML5.zip
          VERSION: ${{ steps.download-windows.outputs.version }}
